CandidateMVC/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using Application.Command;
using Application.DTOs;
using Application.Query;
using CandidateMVC.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json.Linq;
using RestSharp;

namespace CandidateService.Controllers
{
    public class CandidateController : Controller
    {
        private readonly ICandidateQuery candidateQuery;
        private readonly ICandidateCommand candidateCommand;
        private readonly IConfiguration configuration;

        public CandidateController(ICandidateQuery candidateQuery,
                                   IConfiguration configuration,
                                   ICandidateCommand candidateCommand)
        {
            this.candidateQuery = candidateQuery;
            this.configuration = configuration;
            this.candidateCommand = candidateCommand;
        }

        public async Task<IActionResult> Index()
        {
            var model = await candidateQuery.GetAllCandidatesAsync(configuration.GetValue<string>("BaseURLApi"));
            return View(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            var candidate = await candidateQuery.GetCandidateByIdAsync(configuration.GetValue<string>("BaseURLApi"), id.GetValueOrDefault(0));

            if (candidate == null)
                return NotFound();

            return View(candidate);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CandidateId,Name,LastName,DateOfBirth,Email,PhoneNumber,ResumeFile,Jobs")] CandidateDTO candidate)
        {
            if (ModelState.IsValid)
            {
                if (!FileUploadHelper.CheckFileExtension(candidate.ResumeFile, configuration.GetValue<string>("FileExtensions")))
                    throw new Exception("File extension not valid. Please select .pdf or .doc or .docx files.");

                candidate.Resume = await FileUploadHelper.CopyAndCreateFileAsync(candidate.ResumeFile);

                await candidateCommand.CreateCommandAsync(configuration.GetValue<string>("BaseURLApi"), candidate);
                return RedirectToAction(nameof(Index));
            }

            return View(candidate);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var candidate = await candidateQuery.GetCandidateByIdAsync(configuration.GetValue<string>("BaseURLApi"), id.GetValueOrDefault(0));

            if (candidate == null)
                return NotFound();

            return View(candidate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("CandidateId,Name,LastName,DateOfBirth,Email,PhoneNumber,Resume,ResumeFile,Jobs")] CandidateDTO candidate)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await candidateCommand.EditCommandAsync(configuration.GetValue<string>("BaseURLApi"), candidate);
                }
                catch (Exception ex)
                {
                    throw ex;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(candidate);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var candidate = await candidateQuery.GetCandidateByIdAsync(configuration.GetValue<string>("BaseURLApi"), id.GetValueOrDefault(0));

            if (candidate == null)
                return NotFound();

            return View(candidate);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await candidateCommand.DeleteCommandAsync(configuration.GetValue<string>("BaseURLApi"), id);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult GetPartialJob(int countJobs)
        {
            return PartialView("_CandidateJob", new JobDTO { JobIndex = countJobs, JobId = 0, CompanyName = "", Period = "" });
        }
    }
}

CandidateMVC/Views/Candidate/Create.cshtml
@model CandidateDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Candidate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" type="date" data-date-format="dd/MM/yyyy" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resume" class="control-label"></label>
                <input asp-for="ResumeFile" type="file">
                <span asp-validation-for="Resume" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <label asp-for="Jobs" class="control-label"></label>
                <table id="Jobs">
                    <thead>
                        <tr>
                            <th>Company Name</th>
                            <th>Period</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

                <button type="button" onclick="addJob()">
                    Add Job
                </button>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CandidateMVC/Views/Candidate/Delete.cshtml
@model CandidateDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Candidate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resume)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.Resume)
        </dd>
    </dl>
    
    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" asp-for="CandidateId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CandidateMVC/Views/Candidate/Details.cshtml
@model CandidateDTO

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Candidate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resume)
        </dt>
        <dd class = "col-sm-10">
            @Html.ValueFor(model => model.Resume)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CandidateId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CandidateMVC/Views/Candidate/Edit.cshtml
@model CandidateDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Candidate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CandidateId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" type="date" data-date-format="dd/MM/yyyy" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resume" class="control-label"></label>
                <input asp-for="ResumeFile" type="file">
                <input type="hidden" asp-for="Resume">
                <span asp-validation-for="Resume" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <label asp-for="Jobs" class="control-label"></label>
                <table id="Jobs">
                    <thead>
                        <tr>
                            <th>Company Name</th>
                            <th>Period</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Jobs.Count(); i++)
                        {
                            Model.Jobs.ElementAt(i).JobIndex = i;
                            await Html.RenderPartialAsync("_CandidateJob", Model.Jobs.ElementAt(i));
                        }
                    </tbody>
                </table>

                <button type="button" onclick="addJob()">
                    Add Job
                </button>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CandidateMVC/Views/Candidate/Index.cshtml
@model IEnumerable<CandidateDTO>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ValueFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ValueFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.ValueFor(modelItem => item.DateOfBirth)
                    </td>
                    <td>
                        @Html.ValueFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.ValueFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.CandidateId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.CandidateId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.CandidateId">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

CandidateMVC/Views/Candidate/_CandidateJob.cshtml
@model JobDTO

<tr class="partialJobs">
    <td style="display: none;">
        <input type="number" readonly="readonly" disabled="disabled" id="JobId" name="Jobs[@Model.JobIndex].JobId" value="@Model.JobId" maxlength="50" />
    </td>
    <td>
        <input type="text" name="Jobs[@Model.JobIndex].CompanyName" id="CompanyName" value="@Model.CompanyName" maxlength="50" />
    </td>
    <td>
        <input type="text" name="Jobs[@Model.JobIndex].Period" id="Period" value="@Model.Period" placeholder="Desde dd/mm/yyyy Hasta dd/mm/yyyy" />
    </td>
    <td>
        <button type="button" class="btn btn-danger btn-delete" onclick="deleteRow(this);">Delete</button>
    </td>
</tr>

CandidateMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Possumus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Candidate" asp-action="Index">CandidateMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Possumus
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>